apiVersion: v1
kind: Service
metadata:
  name: online-bookstore-service
  namespace: online-bookstore-s224231273
spec:
  type: LoadBalancer
  selector:
    app: online-bookstore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
